name: Wpf Continuous Integration

"on":
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    env:
      App_Packages_Directory: AppPackages
      SigningCertificate: GitHubActionsDemo.pfx
      Solution_Path: AP02023_ws01_WPF_Peekaboo.sln
      Test_Project_Path: AP02023_ws01_WPF_Peekaboo.UITests\AP02023_ws01_WPF_Peekaboo.UITests.csproj
      Wpf_Project_Path: AP02023_ws01_WPF_Peekaboo\AP02023_ws01_WPF_Peekaboo.csproj
      Wap_Project_Directory: AP02023_ws01_WPF_Peekaboo.Package
      Wap_Project_Name: AP02023_ws01_WPF_Peekaboo.Package.wapproj
      Actions_Allow_Unsecure_Commands: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1

      - name: Execute Unit Tests
        run: dotnet test $env:Test_Project_Path
